# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fbe1b1c8b1f4870d12f92d80c58c7886bbd0f32515a0dc2c72d4b10bf69efaada242316bb2a29835ffd90f932bc99a5c3b6123016c0a6443c428a02ad072ffb

test:
  secret_key_base: 68c925b294ea0d482d055053557507659f6a7d1efa888ce8be3aeb032a6888d86ba0a9ac3fd11103f223beccb0fcd890dd63a5f1d9fa3938312ee4e161608066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
